packages:
  - apps/*
  - packages/*
allowBuilds:
  electron: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  unrs-resolver: true
overrides:
  '@electron/node-gyp': 10.2.0-electron.2
minimumReleaseAgeExclude:
  - electron@44.4.5
  - prettier@3.9.9
publicHoistPattern:
  - '*'
